apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: psgress-test
  labels:
    app: psgress-test
spec:
  
  selector:
    matchLabels:
      app: psgress-test
  template:
    metadata:
      labels:
        app: psgress-test
    spec:
      containers:
      - name:  psgress  
        image: dinorg/psgress1      
        env:
         - name: host
           value: "dinor.test"  # yourdbnam
         - name: user
           value: "djdjdj" # your username
         - name: password
           value: "fdfdfdf" #password 
         - name: dbname
           value: "dfdfdf" #dbname  
         - name: HOSTNAME
           valueFrom:
             fieldRef:
               apiVersion: v1
               fieldPath: spec.nodeName 
        volumeMounts:
        - name: azure
          mountPath: /var/logs/pslogs
      volumes:
      - name: azure
        persistentVolumeClaim:
          claimName: azurefile
       
      